msgbox"Hello! pls enter you name! (this here is not a virus!) ",,"Welcome!"
inputbox"Enter Name"
msgbox"ok thats a Cool name! (I like all names!) ",,"Name"
msgbox"So yea what did you do before you fonded this flie?",,"Flie"
inputbox"Enter What you Done before you fonded this!"
